# Establecer la imagen base para .NET Core SDK
FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

# Establecer la imagen base para la construcción
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["TrainEase.csproj", "./"]
RUN dotnet restore "TrainEase.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "TrainEase.csproj" -c Release -o /app/build

# Publicar la aplicación
FROM build AS publish
RUN dotnet publish "TrainEase.csproj" -c Release -o /app/publish

# Construir la imagen final
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TrainEase.dll"]
